# Generated by Django 3.2.7 on 2022-03-03 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubRepositoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(verbose_name='URL репозитория')),
                ('repo_name', models.CharField(default='no name', max_length=100, verbose_name='Название проекта')),
                ('repo_avg_lang', models.CharField(default='no language', max_length=20, verbose_name='Язык программирования(с бо́льшим процентом кода)')),
                ('repo_stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Число звезд')),
                ('repo_forks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Число ответвлений(форков)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано?')),
            ],
            options={
                'verbose_name': 'Карточка GitHub',
                'verbose_name_plural': 'Карточки GitHub',
            },
        ),
    ]
