# Generated by Django 3.2.7 on 2022-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepositorycard',
            name='repo_forks',
        ),
        migrations.RemoveField(
            model_name='githubrepositorycard',
            name='repo_stars',
        ),
        migrations.AddField(
            model_name='githubrepositorycard',
            name='repo_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание репозитория'),
        ),
        migrations.AddField(
            model_name='githubrepositorycard',
            name='repo_licence',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Лицензия репозитория'),
        ),
    ]
