# Generated by Django 3.2.7 on 2022-01-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('native_name', models.CharField(max_length=150, unique=True, verbose_name='Название на родном языке')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('opinion', models.TextField(blank=True, null=True, verbose_name='Мое мнение')),
                ('slug', models.SlugField(max_length=160, null=True, verbose_name='Слаг')),
                ('status', models.CharField(choices=[('pn', 'Запланировано'), ('ga', 'В процессе'), ('rv', 'Повтор'), ('ac', 'Завершено'), ('ab', 'Брошено'), ('pp', 'Отложено')], default='ac', max_length=3, verbose_name='Статус')),
                ('i_recommend', models.BooleanField(default=False, verbose_name='Рекомендую')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/%d', verbose_name='Постер')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('anime_type', models.CharField(choices=[('Ov', 'OVA'), ('Fi', 'Фильм'), ('Se', 'Сериал'), ('On', 'ONA'), ('Sp', 'Спешл')], default='Se', max_length=2, verbose_name='Тип аниме')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('native_name', models.CharField(max_length=150, unique=True, verbose_name='Название на родном языке')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('opinion', models.TextField(blank=True, null=True, verbose_name='Мое мнение')),
                ('slug', models.SlugField(max_length=160, null=True, verbose_name='Слаг')),
                ('status', models.CharField(choices=[('pn', 'Запланировано'), ('ga', 'В процессе'), ('rv', 'Повтор'), ('ac', 'Завершено'), ('ab', 'Брошено'), ('pp', 'Отложено')], default='ac', max_length=3, verbose_name='Статус')),
                ('i_recommend', models.BooleanField(default=False, verbose_name='Рекомендую')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/%d', verbose_name='Постер')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('ISBN', models.CharField(max_length=30, unique=True, verbose_name='Номер книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('native_name', models.CharField(max_length=150, unique=True, verbose_name='Название на родном языке')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('opinion', models.TextField(blank=True, null=True, verbose_name='Мое мнение')),
                ('slug', models.SlugField(max_length=160, null=True, verbose_name='Слаг')),
                ('status', models.CharField(choices=[('pn', 'Запланировано'), ('ga', 'В процессе'), ('rv', 'Повтор'), ('ac', 'Завершено'), ('ab', 'Брошено'), ('pp', 'Отложено')], default='ac', max_length=3, verbose_name='Статус')),
                ('i_recommend', models.BooleanField(default=False, verbose_name='Рекомендую')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/%d', verbose_name='Постер')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Число повторных просмотров')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('native_name', models.CharField(max_length=150, unique=True, verbose_name='Название на родном языке')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('opinion', models.TextField(blank=True, null=True, verbose_name='Мое мнение')),
                ('slug', models.SlugField(max_length=160, null=True, verbose_name='Слаг')),
                ('status', models.CharField(choices=[('pn', 'Запланировано'), ('ga', 'В процессе'), ('rv', 'Повтор'), ('ac', 'Завершено'), ('ab', 'Брошено'), ('pp', 'Отложено')], default='ac', max_length=3, verbose_name='Статус')),
                ('i_recommend', models.BooleanField(default=False, verbose_name='Рекомендую')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/%d', verbose_name='Постер')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('native_name', models.CharField(max_length=150, unique=True, verbose_name='Название на родном языке')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('opinion', models.TextField(blank=True, null=True, verbose_name='Мое мнение')),
                ('slug', models.SlugField(max_length=160, null=True, verbose_name='Слаг')),
                ('status', models.CharField(choices=[('pn', 'Запланировано'), ('ga', 'В процессе'), ('rv', 'Повтор'), ('ac', 'Завершено'), ('ab', 'Брошено'), ('pp', 'Отложено')], default='ac', max_length=3, verbose_name='Статус')),
                ('i_recommend', models.BooleanField(default=False, verbose_name='Рекомендую')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/%d', verbose_name='Постер')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='Число повторных просмотров')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
                'ordering': ['status'],
            },
        ),
    ]
