# Generated by Django 3.2.7 on 2022-02-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='native_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='native_name',
        ),
        migrations.RemoveField(
            model_name='film',
            name='native_name',
        ),
        migrations.RemoveField(
            model_name='game',
            name='native_name',
        ),
        migrations.RemoveField(
            model_name='series',
            name='native_name',
        ),
    ]
