# Generated by Django 3.2.7 on 2021-10-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['rating'], 'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['rating'], 'verbose_name': 'Сериал', 'verbose_name_plural': 'Серилаы'},
        ),
        migrations.AddField(
            model_name='film',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на ознакомление'),
        ),
        migrations.AddField(
            model_name='series',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на ознакомление'),
        ),
    ]
