# Generated by Django 3.2.7 on 2021-10-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0002_auto_20211012_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['rating'], 'verbose_name': 'Сериал', 'verbose_name_plural': 'Сериалы'},
        ),
        migrations.RenameField(
            model_name='film',
            old_name='recomend_to_watch',
            new_name='i_recommend',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='recomend_to_watch',
            new_name='i_recommend',
        ),
    ]
