# Generated by Django 3.2.7 on 2021-10-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0003_auto_20211012_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('native_name', models.CharField(max_length=150, unique=True, verbose_name='Название на родном языке')),
                ('description', models.TextField(verbose_name='Описание')),
                ('opinion', models.TextField(verbose_name='Мое мнение')),
                ('slug', models.SlugField(max_length=160, null=True, verbose_name='Слаг')),
                ('rating', models.IntegerField(choices=[(0, 'Не указан'), (1, 'Хуже некуда'), (2, 'Ужасно'), (3, 'Очень плохо'), (4, 'Плохо'), (5, 'Более-менее'), (6, 'Нормально'), (7, 'Хорошо'), (8, 'Очень хорошо'), (9, 'Великолепно'), (10, 'Шедевр')], default=0, verbose_name='Оценка')),
                ('i_recommend', models.BooleanField(default=False, verbose_name='Рекомендую к ознакомлению')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на ознакомление')),
                ('book_type', models.CharField(choices=[('NO_TYPE', 'Не указано'), ('DEV', 'Разработка'), ('FICTION', 'Художественная литература'), ('GUIDE', 'Справочник'), ('OTHER', 'Другое')], default='NO_TYPE', max_length=100, verbose_name='Тип книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['rating'],
            },
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('native_name', models.CharField(max_length=150, unique=True, verbose_name='Название на родном языке')),
                ('description', models.TextField(verbose_name='Описание')),
                ('opinion', models.TextField(verbose_name='Мое мнение')),
                ('slug', models.SlugField(max_length=160, null=True, verbose_name='Слаг')),
                ('rating', models.IntegerField(choices=[(0, 'Не указан'), (1, 'Хуже некуда'), (2, 'Ужасно'), (3, 'Очень плохо'), (4, 'Плохо'), (5, 'Более-менее'), (6, 'Нормально'), (7, 'Хорошо'), (8, 'Очень хорошо'), (9, 'Великолепно'), (10, 'Шедевр')], default=0, verbose_name='Оценка')),
                ('i_recommend', models.BooleanField(default=False, verbose_name='Рекомендую к ознакомлению')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на ознакомление')),
            ],
            options={
                'verbose_name': 'Видео-игра',
                'verbose_name_plural': 'Видео-игры',
                'ordering': ['rating'],
            },
        ),
    ]
