# Generated by Django 3.2.7 on 2021-10-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0005_auto_20211017_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('native_name', models.CharField(max_length=150, unique=True, verbose_name='Название на родном языке')),
                ('description', models.TextField(verbose_name='Описание')),
                ('opinion', models.TextField(verbose_name='Мое мнение')),
                ('slug', models.SlugField(max_length=160, null=True, verbose_name='Слаг')),
                ('rating', models.IntegerField(choices=[(0, 'Не указан'), (1, 'Хуже некуда'), (2, 'Ужасно'), (3, 'Очень плохо'), (4, 'Плохо'), (5, 'Более-менее'), (6, 'Нормально'), (7, 'Хорошо'), (8, 'Очень хорошо'), (9, 'Великолепно'), (10, 'Шедевр')], default=0, verbose_name='Оценка')),
                ('i_recommend', models.BooleanField(default=False, verbose_name='Рекомендую к ознакомлению')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на ознакомление')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Постер')),
                ('product_type', models.CharField(choices=[('film', 'Фильм'), ('series', 'Сериал'), ('game', 'Игра'), ('book', 'Книга')], max_length=10, verbose_name='Тип произведения')),
            ],
            options={
                'verbose_name': 'Произведение',
                'verbose_name_plural': 'Произведения',
                'ordering': ['-rating'],
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.DeleteModel(
            name='VideoGame',
        ),
    ]
