# Generated by Django 3.2.7 on 2021-10-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0006_auto_20211022_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_anime',
            field=models.BooleanField(default=False, verbose_name='Аниме'),
        ),
    ]
