# Generated by Django 3.2.7 on 2021-10-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0007_product_is_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='opinion',
            field=models.TextField(blank=True, null=True, verbose_name='Мое мнение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/%Y/%m/%d', verbose_name='Постер'),
        ),
    ]
