# Generated by Django 3.2.7 on 2021-10-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0008_auto_20211026_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('film', 'Фильм'), ('series', 'Сериал'), ('anime', 'Аниме'), ('game', 'Игра'), ('book', 'Книга')], max_length=10, verbose_name='Тип произведения'),
        ),
    ]
