# Generated by Django 3.2.7 on 2021-11-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0009_alter_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_anime',
        ),
    ]
