# Generated by Django 3.2.7 on 2021-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0010_remove_product_is_anime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
