# Generated by Django 3.2.7 on 2022-01-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0011_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Число повторных ознакомлений'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pn', 'Запланировано'), ('ga', 'В процессе (Ознакомляюсь)'), ('rv', 'Повтор'), ('ac', 'Завершено'), ('ab', 'Брошено'), ('pp', 'Отложено')], default='ac', max_length=3, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='i_recommend',
            field=models.BooleanField(default=False, verbose_name='Рекомендую'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
