# Generated by Django 3.2.7 on 2022-01-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0013_rating_ratingitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['status'], 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='rating_system',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myList.rating', verbose_name='Рейтинг'),
        ),
    ]
