# Generated by Django 3.2.7 on 2022-01-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myList', '0014_auto_20220113_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_system',
        ),
        migrations.AddField(
            model_name='rating',
            name='parent_product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myList.product', verbose_name='Произведение'),
        ),
    ]
